<a href="https://colab.research.google.com/github/alissonwatanabe/Curso-Python-para-Data-Science-Alura/blob/main/PROGRAMA%C3%87%C3%83O_DE_SISTEMAS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**QUESTÃO 1** Escreva um programa que preencha um vetor de dez posições. Em seguida, apresente somente os números positivos armazenados no vetor.

In [ ]:
from random import randrange

n=[]
a=[]
for i in range(10):
  n.append(randrange(-10, 10))

print("MATRIZ ORIGINAL: ",n)

for i in range(10):
  if n[i] > 0:
    a.append(n[i])

print("\nMATRIZ COM NUMEROS POSITIVOS: ",a)


MATRIZ ORIGINAL:  [-4, -3, -10, -9, 0, -7, -2, 1, 3, 8]

MATRIZ COM NUMEROS POSITIVOS:  [1, 3, 8]


**QUESTÃO 2** Escreva um programa que preencha um vetor com dez números reais, calcule e mostre a quantidade de números negativos e a soma dos números positivos desse vetor.

---



In [ ]:
from random import randrange

n=[]
a=[]

cont = 0

for i in range(10):
  n.append(randrange(-10, 10))

print("MATRIZ ORIGINAL: ",n)

for i in range(10):
  if n[i] < 0:
    cont += 1

print("\nQUANTIDADE DE NÚMEROS NEGATIVOS NA MATRIZ: ",cont)

for i in range(10):
  if n[i] > 0:
    a.append(n[i])    

print("\nSOMA DOS NÚMERO POSITIVOS DA MATRIZ: ",sum(a))

MATRIZ ORIGINAL:  [8, -2, 5, -10, -3, 7, -1, -1, 1, -10]

QUANTIDADE DE NÚMEROS NEGATIVOS NA MATRIZ:  6

SOMA DOS NÚMERO POSITIVOS DA MATRIZ:  21


**QUESTÃO 4**
Escreva um programa que preencha um vetor de trinta posições com números inteiros. Depois
do preenchimento, realize a divisão do número da posição i pelo maior número armazenado no
vetor. O resultado da divisão deve substituir o número armazenado na posição i. Repita a
divisão para os i números armazenados no vetor. Por fim, apresente o vetor atualizado.


In [ ]:
from random import randrange

n=[]
for numero in range(1,31):
  n.append(randrange(0,1000))
  maior = max(n)

print(f'VETOR DE TRINTA POSIÇÕES: ', n)
print(f'MAIOR VALOR DO VETOR: ',maior)

vetor_att=[]
for i in n:
  a = round((i/maior), 3)
  vetor_att.append(a)

print(f'VETOR RESULTANTE:  ', vetor_att)

VETOR DE TRINTA POSIÇÕES:  [242, 761, 894, 211, 526, 527, 574, 183, 371, 883, 564, 527, 54, 868, 454, 869, 913, 989, 588, 887, 688, 173, 216, 872, 506, 573, 522, 335, 921, 547]
MAIOR VALOR DO VETOR:  989
VETOR RESULTANTE:   [0.245, 0.769, 0.904, 0.213, 0.532, 0.533, 0.58, 0.185, 0.375, 0.893, 0.57, 0.533, 0.055, 0.878, 0.459, 0.879, 0.923, 1.0, 0.595, 0.897, 0.696, 0.175, 0.218, 0.882, 0.512, 0.579, 0.528, 0.339, 0.931, 0.553]


**QUESTÃO 6**
Escreva um programa que dada uma matriz qualquer (o usuário deve informar o número de
linhas e o número de colunas), retorne o número de linhas nulas da matriz. Uma linha nula é
uma linha que possui apenas valores zeros.

In [ ]:
import numpy as np
import random

l = int(input("Digite o número de linhas da matriz : "))
c = int(input("\nDigite o número de colunas da matriz : "))

array = np.random.randint(2, size=(l, c)) 

for i in range(l):
    if np.all(array[i] == 0):
      print("\nA linha {} é nula nula ".format(i+1))
  
    else:
      print("A linha {} mão é nula" .format(i+1))
  
print("\n MATRIZ")
print(array)


Digite o número de linhas da matriz : 2

Digite o número de colunas da matriz : 2

A linha 1 é nula nula 
A linha 2 mão é nula

 MATRIZ
[[0 0]
 [1 0]]


**QUESTÃO 8**
Elabore um programa que preencha uma matriz 5 X 5 e crie dois vetores de cinco posições
cada um, que contenham, respectivamente, as somas das linhas e das colunas da matriz. O
programa deverá escrever a matriz e os vetores criados.

In [ ]:
import numpy as np
import random

array = np.random.randint(100, size=(5, 5)) 
linha = []
coluna = []

print("MATRIZ")
print(array)

print("\nSOMA LINHAS")
linha = [(array[0,0] + array[0,1] +array[0,2] + array[0,3] + array[0,4]), (array[1,0] + array[1,1] +array[1,2] + array[1,3] + array[1,4]), (array[2,0] + array[1,1] +array[2,2] + array[2,3] + array[2,4]), (array[3,0] + array[3,1] +array[3,2] + array[3,3] + array[3,4]), (array[4,0] + array[4,1] +array[4,2] + array[4,3] + array[4,4])]
print(linha)

print("\nSOMA COLUNAS")
coluna = [(array[0,0] + array[1,0] +array[2,0] + array[3,0] + array[4,0]), (array[0,1] + array[1,1] + array[2,1] + array[3,1] + array[4,1]), (array[0,2] + array[1,2] +array[2,2] + array[3,2] + array[4,2]), (array[0,3] + array[1,3] +array[2,3] + array[3,3] + array[4,3]), (array[0,4] + array[1,4] +array[2,4] + array[3,4] + array[4,4])]
print(coluna)



In [156]:
from re import I
import numpy as np
import random

array = np.random.randint(100, size=(5, 5)) 
linha = []
coluna = []
x = []
y = [] 

print("MATRIZ")
print(array)

i = 0
j = 0

for i in range(5):
  for j in range(5):
    a = array[j]
    linha.append(a)
    x = sum(linha[i])
  y.append(x)

print("\nSOMA DAS LINHAS: ", y)

MATRIZ
[[72 61 93 26 18]
 [20 61 34 24 17]
 [37  4 78 90 32]
 [65 52 61 37  4]
 [26 26 90 16 31]]

SOMA DAS LINHAS:  [270, 156, 241, 219, 189]


**QUESTÃO 10**
Uma matriz esparsa é uma matriz que tem mais de 2/3 de seus elementos iguais a zero.
Implemente um programa que leia uma matriz qualquer e informe se tal matriz é esparsa. É o
usuário quem deve passar o número de linhas e o número de colunas da matriz.

In [1]:
import numpy as np
import random

l = int(input("Digite o número de linhas da matriz : "))
c = int(input("\nDigite o número de colunas da matriz : "))

array = np.random.randint(3, size=(l, c)) 

contador = 0
for i in range(l):
   for j in range(c):
     if array[i,j] == 0:
       contador += 1

print("MATRIZ")
print(array)
print("\nQuantidade de zeros na matriz = ", contador)

n = l*c
if contador > (2*n/3):
  print("A matriz é esparsa")
else:
  print("A matriz não é esparsa")


Digite o número de linhas da matriz : 10

Digite o número de colunas da matriz : 10
MATRIZ
[[0 1 2 1 0 2 1 0 2 0]
 [2 1 1 2 0 2 1 0 2 2]
 [1 1 2 1 0 2 0 0 2 0]
 [2 0 0 1 2 0 2 0 1 2]
 [1 0 1 2 2 2 1 1 0 0]
 [0 2 0 2 1 0 0 0 0 2]
 [2 1 2 1 0 2 0 2 1 0]
 [0 1 2 2 2 1 2 1 1 2]
 [2 0 1 1 2 1 1 2 2 1]
 [0 0 1 1 2 2 1 0 1 0]]

Quantidade de zeros na matriz =  32
A matriz não é esparsa


**QUESTÃO 12**
A prefeitura de uma cidade realizou uma pesquisa para coletar informações sobre o salário, a
idade e o número de filhos de sua população adulta. Tais informações compõem o registro
habitante. Para auxiliar na pesquisa, implemente um programa que receba os dados de 12
pessoas. Em seguida, os seguintes cálculos devem ser realizados e apresentados:

**a)** A média de salário da população

**b)** A média do número de filhos

**c)** O maior salário recebido na cidade

**d)** O menor salário recebido na cidade

**e)** O percentual de homens com salário superior a R$ 1.000,00

**f)** O percentual de mulheres com salário superior a R$ 1.000,00

In [ ]:
import pandas as pd
import numpy as np

salario = []
idade = []
filhos = []
sexo = []
conth = 0
contm = 0
conthomem = 0
contmulher = 0
r = 12

for i in range(r):
  a = int(input("\n Pessoa {}, digite o salário: " .format(i+1)))
  salario.append(a)
  b = int(input("\n Pessoa {}, digite idade: " .format(i+1)))
  idade.append(b)
  c = int(input("\n Pessoa {}, digite o numero de filhos: " .format(i+1)))
  filhos.append(c) 
  d = input("\n Pessoa {}, é homem? (S) ou (N): " .format(i+1))
  sexo.append(d) 
  if (sexo[i] == 's'):
    conth += 1
  elif (sexo[i] == 'n'):
    contm += 1
  if (salario[i] > 1000) and (sexo[i] == 's'):
    conthomem += 1
  elif (salario[i] > 1000) and (sexo[i] == 'n'):
    contmulher += 1

print("\nSalários: ",salario)
print("Idades: ",idade)
print("Filhos: ",filhos)

mediasalario = np.mean(salario)
mediafilho = np.mean(filhos)
print("\na) Média de Salário: ",mediasalario)
print("b) Média de Filhos: ",mediafilho)

print("c) Maior Salário: ",max(salario))
print("d) Menor Salário: ",min(salario))

if conthomem > 0:
  print("e) Porcentagem de Homens com salário maior que R$ 1000,00: {}%".format(conth/conthomem*100))
else:
  print("e) Porcentagem de Homens com salário maior que R$ 1000,00: 0%")

if contmulher > 0:
  print("f) Porcentagem de Mulheres com salário maior que R$ 1000,00: {}%".format(contm/contmulher*100))
else: 
  print("f) Porcentagem de Mulheres com salário maior que R$ 1000,00: 0%")

**QUESTÃO 14**
Implemente um programa para criptografar uma frase fornecida pelo usuário. Na criptografia,
as vogais da frase devem ser trocadas pelo caractere #.
Exemplo:
Frase: meu fusca preto
Saída: m## f#sc# pr#t#

In [4]:
frase = input("Escreva sua Frase: ")
x = frase.upper()

a = x.replace("A", "#")
e = a.replace("E", "#")
i = e.replace("I", "#")
o = i.replace("O", "#")
u = o.replace("U", "#")

print(u)

Escreva sua Frase: PROGRAMAÇÃO DE SISTEMAS
PR#GR#M#ÇÃ# D# S#ST#M#S


**QUESTÃO 16**
Implemente um programa que receba uma frase e faça a criptografia dela, substituindo as
vogais pelos seguintes números: a = 1, e = 2, i = 3, o = 4 e u = 5.

In [3]:
frase = input("Escreva sua Frase: ")
x = frase.upper()

a = x.replace("A", "1")
e = a.replace("E", "2")
i = e.replace("I", "3")
o = i.replace("O", "4")
u = o.replace("U", "5")

print(u)

Escreva sua Frase: PROGRAMAÇÃO DE SISTEMAS
PR4GR1M1ÇÃ4 D2 S3ST2M1S


**QUESTÃO 18**
Faça um programa que se comporte como vírus, duplicando cada uma das palavras digitadas
pelo usuário.
Exemplo:
Frase: EU ESTOU NA ESCOLA
Saída: EU EU ESTOU ESTOU NA NA ESCOLA ESCOLA

In [2]:
a = input("Escreva a frase desejada: ")

x = a.split()
l = len(x)
resultado = []

for i in range(l):
  dup = (x[i] + " " + x[i])
  resultado.append(dup)
   

' '.join(resultado)




  

Escreva a frase desejada: PROGRAMAÇÃO DE SISTEMAS


'PROGRAMAÇÃO PROGRAMAÇÃO DE DE SISTEMAS SISTEMAS'