<a href="https://colab.research.google.com/github/alissonwatanabe/Curso-Python-para-Data-Science-Alura/blob/main/Recursos_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [40]:
!python --version

Python 3.7.13


# 1.3 Trabalhando com arrays Numpy

In [41]:
import numpy as np

In [42]:
km = np.loadtxt('carros-km.txt', dtype = int)

In [43]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [44]:
anos = np.loadtxt('carros-anos.txt', dtype = int)

In [45]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [46]:
km_media = km / (2022 - anos)
km_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

In [47]:
type(km_media)

numpy.ndarray

### Obtendo a quilometragem média por ano

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [48]:
2+2

4

### Subtração ($-$)

In [49]:
2-2

0

### Multiplicação ($*$)

In [50]:
2*3

6

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [51]:
10/3

3.3333333333333335

In [52]:
10//3

3

### Exponenciação ($**$)

In [53]:
2**3

8

### Resto da divisão ($\%$)

In [54]:
10%3

1

### Expressões matemáticas

In [55]:
5 * 2 + 3 * 2

16

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [56]:
5*2

10

In [57]:
_ + 3 * 2

16

In [58]:
_ / 2

8.0

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [59]:
ano_atual = 2022
ano_fabricacao = 2003

In [60]:
km_total = 44410.0 

In [61]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0 

km_medio = km_total / (ano_atual - ano_fabricacao)

km_total = km_total + km_medio
km_total

46747.36842105263

In [62]:
ano_atual = 2022
ano_fabricacao = 2003
km_total = 44410.0

km_medio = km_total / (ano_atual - ano_fabricacao)
km_total += km_medio

km_total


46747.36842105263

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [63]:
ano_atual, ano_fabricacao, km_total = 2022, 2003, 44410.0

In [64]:
ano_atual

2022

In [65]:
ano_fabricacao

2003

In [66]:
km_total

44410.0

In [67]:
ano_atual, ano_fabricacao, km_total = 2022, 2003, 44410.0
km_medio = km_total / (ano_atual - ano_fabricacao)
km_total += km_medio

km_total

46747.36842105263

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [68]:
ano_atual = 2022

In [69]:
type(ano_atual)

int

In [70]:
km_total = 44410.0

In [71]:
type(km_total)

float

### Booleanos

In [72]:
zero_km = True

In [73]:
type(zero_km)

bool

### Strings

In [74]:
nome = 'Jetta Variant'
nome

'Jetta Variant'

In [75]:
nome = 'Jetta "Variant"'
nome

'Jetta "Variant"'

In [76]:
carro = '''
  nome
  idade
  nota
'''

In [77]:
carro

'\n  nome\n  idade\n  nota\n'

In [78]:
type(carro)

str

### None

In [79]:
quilometragem  = None
quilometragem

In [80]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [81]:
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [82]:
type (a)

int

In [83]:
type(b)

int

In [84]:
type(c)

str

In [85]:
type(d)

str

In [86]:
a+b

30

In [87]:
c+d

'Python é legal'

In [88]:
str(a)

'10'

In [89]:
c+str(a)

'Python é 10'

### Conversões de tipo

Funções int(), float(), str()

In [90]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

text + str(int(Km/(Ano_atual-Ano_fabricacao)))+' km'

'A quilometragem média do veículo é 5000 km'

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [91]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [92]:
# Isto é um comentário
ano_atual = 2019
ano_atual

2019

In [93]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

2019

In [94]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

2019

In [95]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

In [96]:
print('Olá {}!' .format('Alisson'))

Olá Alisson!


In [97]:
print('Olá {}! Esse é seu acesso de número {}'.format('Alisson', 32))

Olá Alisson! Esse é seu acesso de número 32


In [98]:
print('Olá {nome}! Esse é seu acesso de número {acessos}'.format(nome = 'Alisson', acessos = 32))

Olá Alisson! Esse é seu acesso de número 32


In [99]:
nome = 'Alisson'
acessos = 32

In [100]:
print('Olá {nome}! Esse é seu acesso de número {acessos}')

Olá {nome}! Esse é seu acesso de número {acessos}


In [101]:
print(f'Olá {nome}! Esse é seu acesso de número {acessos}')

Olá Alisson! Esse é seu acesso de número 32


## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [102]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [103]:
type(Acessorios)

list

### Lista com tipos de dados variados

In [104]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [105]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [106]:
carros = [Carro_1, Carro_2]
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [107]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [108]:
'4x4' in Acessorios

False

In [109]:
'Rodas de liga' in Acessorios

True

In [110]:
'Rodas de liga' not in Acessorios

False

In [111]:
'4x4' not in Acessorios

True

In [112]:
'Rodas de liga' in Carro_1

False

## *A + B*

Concatena as listas *A* e *B*.

In [113]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [114]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [115]:
len(Acessorios)

8

## *len(A)*

Tamanho da lista A.

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [116]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [117]:
Acessorios[4]

'Ar condicionado'

In [118]:
Acessorios[0]

'Rodas de liga'

In [119]:
Acessorios[0:2]

['Rodas de liga', 'Travas elétricas']

In [120]:
Acessorios[-1]

'Sensor de chuva'

In [121]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [122]:
carros[0][0]

'Jetta Variant'

In [123]:
carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [124]:
carros[0][-2][2]

'Piloto automático'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [125]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [126]:
Acessorios[2:6]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento']

In [127]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [128]:
Acessorios[:6]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [129]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [130]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [131]:
Acessorios.append('4 x 4')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [132]:
Acessorios.pop()

'4 x 4'

In [133]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [134]:
Acessorios.pop(3)

'Rodas de liga'

In [135]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [136]:
Acessorios_2 = Acessorios.copy()

In [137]:
Acessorios_2.append('teste')
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'teste']

In [138]:
Acessorios_3 = Acessorios[:]

In [139]:
Acessorios_3

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [140]:
Acessorios_4 = Acessorios[0:2]

In [141]:
Acessorios_4

['Ar condicionado', 'Bancos de couro']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [142]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [143]:
for item  in Acessorios:
  print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [144]:
range(10)

range(0, 10)

In [145]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [146]:
for i in range (10):
  print(i**2)

0
1
4
9
16
25
36
49
64
81


In [147]:
quadrado = []
for i in range (10):
  quadrado.append(i**2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [148]:
[i**2 for i in range (10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [149]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [150]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [151]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [152]:
Acessorios = []

for lista in dados:
  for item in lista:
    Acessorios.append(item)

Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [153]:
list(Acessorios)
Acessorios.sort()
set(Acessorios)

{'4 X 4',
 'Ar condicionado',
 'Bancos de couro',
 'Central multimídia',
 'Controle de estabilidade',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Freios ABS',
 'Painel digital',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Teto panorâmico',
 'Travas elétricas',
 'Vidros elétricos'}

### List comprehensions

In [154]:
[item for lista in dados for item in lista]  

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [155]:
list(set(lista))

['Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Câmbio automático',
 'Central multimídia',
 'Controle de estabilidade',
 'Freios ABS',
 'Vidros elétricos']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [156]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [157]:
for lista in dados:
  if (lista[2]) == True:
    print(lista[0])

DS5
A5


In [158]:
zero_km_s = []
zero_km_n = []

for lista in dados:
  if (lista[2]) == True:
    zero_km_s.append(lista)
  else: 
    zero_km_n.append(lista)

zero_km_n

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [159]:
zero_km_s

[['DS5', 2019, True], ['A5', 2019, True]]

### List comprehensions

In [160]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [161]:
zero_km_s, zero_km_n = [], []

for lista in dados:
  if (lista[2]) == True:
    zero_km_s.append(lista)
  else: 
    zero_km_n.append(lista)

In [162]:
zero_km_s

[['DS5', 2019, True], ['A5', 2019, True]]

In [163]:
zero_km_n

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [164]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [165]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [166]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [167]:
a, b, c = [], [] , []

for lista in dados:
  if (lista[1] <= 2000):
    a.append(lista)
  elif (lista[1] > 2000 and lista[1] <= 2010):
    b.append(lista)
  else:
    c.append(lista)

In [168]:
a

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [169]:
b

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [170]:
c

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [171]:
a, b, c = [], [] , []

for lista in dados:
  if (lista[1] <= 2000):
    a.append(lista)
  elif ( 2000 < lista[1] <= 2010):
    b.append(lista)
  else:
    c.append(lista)

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [172]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [173]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [174]:
import numpy as np

In [175]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [176]:
from numpy import arange

In [177]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [178]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [179]:
km = np.array([1000, 2300, 4987, 1500])

In [180]:
km

array([1000, 2300, 4987, 1500])

In [181]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [182]:
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)

In [183]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [184]:
km.dtype

dtype('int64')

### Arrays com duas dimensões

In [185]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [186]:
acessorios = np.array(dados)

In [187]:
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [188]:
km.shape

(258,)

In [189]:
acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [190]:
np_array = np.arange(1000000)

In [191]:
py_list = list(range(1000000))

In [192]:
%time for _ in range(100): np_array *= 2

CPU times: user 225 ms, sys: 15.3 ms, total: 241 ms
Wall time: 252 ms


In [193]:
%time for _ in range(100):py_list = [x*2 for x in py_list]

CPU times: user 9.63 s, sys: 2.36 s, total: 12 s
Wall time: 12.3 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [194]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [195]:
idade = 2019 - anos

TypeError: ignored

In [196]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [197]:
idade = 2019 - anos

In [198]:
idade

array([16, 28, 29,  0, 13])

### Operações entre arrays

In [199]:
km_media = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [200]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

### Operações com arrays de duas dimensões

In [201]:
dados = np.array([km, anos])

In [202]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [203]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [204]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [205]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [206]:
km_media = dados[0] / (2019-dados[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [207]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [208]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
contador[0]

0

In [210]:
item = 6
index = item - 1
contador[index]

5

In [211]:
contador[-1]

9

In [212]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [213]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [234]:
dados[1][2]

1990.0

In [215]:
dados[1, 2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [216]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [217]:
contador [1:4]

array([1, 2, 3])

In [218]:
contador[1:8:2]

array([1, 3, 5, 7])

In [219]:
contador[::2]

array([0, 2, 4, 6, 8])

In [220]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [221]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [222]:
dados[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [223]:
(dados[:, 1:4][0] / (2019 - dados[:, 1:4][1]))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ 204.        , 1280.10344828,           nan])

In [237]:
dados[:1, 1:4]

array([[ 5712., 37123.,     0.]])

In [239]:
dados[:, 1:4][0]

array([ 5712., 37123.,     0.])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [224]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [226]:
contador[contador > 5]

array([6, 7, 8, 9])

In [227]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [228]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

# 5.4 Atributos e métodos de arrays Numpy

In [240]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [241]:
dados.shape

(2, 5)

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [243]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [244]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [245]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [246]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [250]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [248]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [252]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [254]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [ ]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.